version: "3.9"
services:
  frontend:
    image: frontend
    networks:
      - github-repo-notes
    ports:
      - "3000:3000"
  backend:
    image: backend
    networks:
      - github-repo-notes
    ports:
      - "3001:3001"
  mongo:
    image: mongo:latest
    networks:
      - github-repo-notes
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
networks:
  github-repo-notes:
    driver: bridge
volumes:
  mongo-data:
    driver: local
